---
swagger: '2.0'
info:
  version: v1
  title: STATAPI Public
host: localhost:56280
schemes:
- http
- https
paths:
  "/api/Orders/{senderZipCode}/{recipZipCode}":
    get:
      tags:
      - Orders
      summary: Get orders
      description: This endpoint facilitates the retrieval of a list of orders.
      operationId: Orders_GetOrders
      consumes: []
      produces:
      - application/json
      - text/json
      parameters:
      - name: senderZipCode
        in: path
        required: true
        type: string
      - name: recipZipCode
        in: path
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
          examples:
            application/json:
              TrackingNumber: ''
        '400':
          description: BadRequest
    post:
      tags:
      - Orders
      operationId: Orders_SetCustomerbyId
      consumes: []
      produces:
      - application/json
      - text/json
      parameters:
      - name: CustomerId
        in: query
        required: true
        type: integer
        format: int32
      - name: senderZipCode
        in: path
        required: true
        type: string
      - name: recipZipCode
        in: path
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: boolean
  "/api/Orders":
    get:
      tags:
      - Orders
      summary: Get orders
      description: This endpoint facilitates the retrieval of a list of orders.
      operationId: Orders_GetOrders
      consumes: []
      produces:
      - application/json
      - text/json
      responses:
        '200':
          description: OK
          schema:
            type: object
          examples:
            application/json:
              TrackingNumber: ''
        '400':
          description: BadRequest
    post:
      tags:
      - Orders
      operationId: Orders_SetCustomerbyId
      consumes: []
      produces:
      - application/json
      - text/json
      parameters:
      - name: CustomerId
        in: query
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            type: boolean
definitions: {}
