---
openapi: 3.0.0
info:
  # version: v1
  title: STAT API Documentation
  x-logo:
    # url: '../logo.png'
    url: 'https://arulest.github.io/STATAPI_Order/logo.png'
    # url: "../vNEXT_V1/logo.png"
    altText: STAT logo

tags:
  - name: Orders
    description: |
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Orders module is designed to streamline the management of orders within the application. It provides a comprehensive set of endpoints and functionalities that allow users to retrieve orders. This module serves as the backbone for order processing, ensuring a seamless and efficient experience for the customers and administrators.

      Key features of the Orders module include: 


        •	**Order Creation:** Users can submit new orders through dedicated endpoints, specifying essential details such as collection and delivery location, quantities and price and tracking information. 
      
      
        •	**Order Retrieval:** Retrieve detailed information about existing orders, including order tracking number, status, collection and delivery location, and customer details. 
      
      
        •	**Order Status Tracking:** Easily monitor the status of orders, from creation to shipment and delivery, enabling real-time order tracking for customers and staff. 
x-tagGroups:
  - name: General
    tags:
      - Orders
     
paths:
  /api/V2/Createorder:
    post:
      tags:
        - Orders
      summary: Create an Order
      operationId: Orders_CreateOrder
      description: This API endpoint facilitates the creation of a customer's order by capturing essential information such as quantities, prices, and location details. 
      parameters:
        - in: body
          name: orderDto
          required: true
          schema:
            $ref: '#/components/schemas/CreateOrderInDto'
      responses:
        "200":
          description: OK successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderOutDto'
        "400":
          description: |
            BadRequest: 
            <ul>
              <li>Customer not located or authenticated.</li>
              <li>Either this order\'s collection or delivery AddressLine1 is not available.</li>
              <li>Either this order\'s collection or delivery City code is not available.</li>
              <li>Either this order\'s collection or delivery State is not available.</li>
              <li>Either this order\'s collection or delivery zip code is not available.</li>
              <li>Either this order\'s delivery zip code is not serviceable at all or it cannot be serviced from your local service area. Please contact STAT customer service if you believe this to be inaccurate. We apologize for the inconvenience.</li>
              <li>Invalid  Shipping Label Size</li>
              <li>ModelState is Not Valid</li>
              <li>Not authorized.</li>
              <li>Order Could not Save Correctly, please check object Body</li>
              <li>orders with adult signature required to be direct</li>
              <li>Selected price set not available at this time. Use api/PriceSets to get current list of available customer price sets.</li>
            </ul>
      requestBody:
        name: customerDto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderInDto'
        description: Order request body schema description.
        required: true 
  
components:
  schemas:
    Collectionlocation:
      type: object
      required:
        - AddressLine1
        - AddressLine2
        - City
        - CompanyName
        - ContactName
        - Country
        - Email
        - Phone
        - PostalCode
        - State
      properties:
        ContactName:
          type: string
          description: Name of the contact person of collection
          minLength: 0
          maxLength: 50
        CompanyName:
          type: string
          description: Name of the company of the collection location 
          minLength: 0
          maxLength: 50
        AddressLine1:
          type: string
          description: Line 1 of the collection location address.
          minLength: 0
          maxLength: 50
        AddressLine2:
          type: string
          description: Line 2 of the collection location address. 
          minLength: 0
          maxLength: 50
        City:
          type: string
          description: City of the collection location
          minLength: 0
          maxLength: 50
        State:
          type: string
          description: State of the collection location  
          minLength: 0
          maxLength: 50
        PostalCode:
          type: string
          description: Postal code of the collection and delivery location
          minLength: 0
          maxLength: 50
        Country:
          type: string
          description: Country of the collection location
          minLength: 0
          maxLength: 50
        Comments:
          type: string
          description: Free text field to input the additional information 
          minLength: 0
          maxLength: 512
        Email:
          type: string
          description: Email address of the contact person    
          minLength: 0
          maxLength: 512
        Phone:
          type: string
          description: Phone number of the contact person in collection  
          minLength: 
          maxLength: 50
        LatitudeLongitude:
          type: string
          description: Lat & Long coordinates to collect the package
          minLength: 0
          maxLength: 100
      example:
        ContactName : "Demo Collection-11" 
        CompanyName : "Collection Company-11" 
        AddressLine1 : "2334 Cedar Crest Blvd" 
        AddressLine2 : "None" 
        City : "Dallas" 
        State : "TX" 
        PostalCode : "75203" 
        Country : "United States" 
        Comments : null 
        Email : "pharma@yopmail.com" 
        Phone : "9517538640" 
        LatitudeLongitude : "32.7334,-96.79282" 
      xml:
        name: Collectionlocation
    Deliverylocation:
      type: object
      required:
        - AddressLine1
        - AddressLine2
        - City
        - CompanyName
        - ContactName
        - Country
        - Email
        - Phone
        - PostalCode
        - State
      properties:
        ContactName:
          type: string
          description: Name of the contact person of delivery location
          minLength: 0
          maxLength: 50
        CompanyName:
          type: string
          description: Name of the company of the delivery location 
          minLength: 0
          maxLength: 50
        AddressLine1:
          type: string
          description: Line 1 of the collection & delivery location address.
          minLength: 0
          maxLength: 50
        AddressLine2:
          type: string
          description: Line 2 of the delivery location address.    
          minLength: 0
          maxLength: 50
        City:
          type: string
          description: City of the delivery location 
          minLength: 0
          maxLength: 50
        State:
          type: string
          description: State of the delivery location    
          minLength: 0
          maxLength: 50
        PostalCode:
          type: string
          description: Postal code of the delivery location 
          minLength: 0
          maxLength: 50
        Country:
          type: string
          description: Country of the delivery location
          minLength: 0
          maxLength: 50
        Comments:
          type: string
          description: Free text field to input the additional information 
          minLength: 0
          maxLength: 512
        Email:
          type: string
          description: Email address of the contact person  
          minLength: 0
          maxLength: 512
        Phone:
          type: string
          description: Phone number of the contact person in delivery
          minLength: 0
          maxLength: 50
        LatitudeLongitude:
          type: string
          description: Lat & Long coordinates to deliver the package 
          minLength: 0
          maxLength: 100
      example:
        Zone : null 
        ID : "8c7630b9-5a2c-4c1e-8eb5-88b864ca1a37" 
        ContactName : "Texaco Austin schedule-10" 
        CompanyName : "Texaco Austin schedule-10" 
        AddressLine1 : "6018 Atwood St" 
        AddressLine2 : "-" 
        City : "Austin" 
        State : "TX" 
        PostalCode : "78741" 
        Country : "United States" 
        Comments : "test" 
        Email : "uzumaki@yopmail.com" 
        Phone : "75315945610" 
        Category : null 
        LatitudeLongitude : null 
      xml:
        name: Deliverylocation

    CreateOrderInDto:
      type: object
      required:
        - CODAmount
        - Comments
        - DeclaredValue
        - Description
        - PriceSet
        - PurchaseOrderNumber
        - Quantity
        - SignatureType
        - Weight
      properties:
        Refrigerated:
          type: boolean
          description: This tells whether the product is refrigerated before or during the shipment.  
            The possible values are “true/false”. True represents that the product is refrigerated and false demotes it is not refrigerated  
        TrackingNumber:
          type: string
          description: The tracking number acts as a unique identifier to track the package in real time during the shipment.
          minLength: 0
          maxLength: 50      
        ShippinglabelSize:
          type: string
          description: Represents the size of the shipping label
          minLength: 0
          maxLength: 50     
        Format:
          type: string
          description: The format in which the file should be downloaded. 
          minLength: 0
          maxLength: 50         
        RequestedBy:
          type: string
          description: The individual who requested the order 
          minLength: 0
          maxLength: 50
        Description:
          type: string
          description: This is a free text field where the special instructions about the product, shipment are added
          minLength: 0
          maxLength: 2000  
        Comments:
          type: string
          description: This is a free text field where the special instructions about the product, shipment are added
          minLength: 0
          maxLength: 2000  
        CollectionContactName  :
          type: string
          description: Name of the person from whom the package should be collected
          minLength: 0
          maxLength: 50     
        CollectionCODRequired :
          type: boolean
          description: This indicates whether collection COD is required  
            The potential values are "Yes/No," where "Yes" signifies that the COD is required, and "No" signifies that it is not required.  
        CODAmount:
          type: number
          format: double
          description: The amount to be collected during the time of delivery 
        CollectionSignatureRequired:
          type: boolean
          description: This indicates whether obtaining a signature from the recipient is necessary after package collection.  
            The potential values are "Yes/No," where "Yes" signifies that the signature is required, and "No" signifies that it is not required.  
        Weight:
          type: number
          format: double
          description: Weight of the package 
        Quantity:
          type: integer
          format: int32
          description: Order quantity 
        PriceSet:
          type: string
          description: Priceset of the package 
          minLength: 0
          maxLength: 50
        DeclaredValue:
          type: number
          format: double
          description: The amount value declared for the order  
        DeliverySignatureRequired:
          type: boolean
          description: Indicates whether a signature is necessary from the recipient upon package delivery.  
            The potential values are "Yes/No," where "Yes" signifies that the signature is required, and "No" signifies that it is not required. 
        SignatureType :
          type: string
          description: This denotes whether the signature should be received from the desired contact.   
            The possible values are “Direct/Indirect” where “Direct” signifies that the signature needs to be received from the desired person and “Indirect” signifies that it is not needed to be collected from the desired person
          minLength: 0
          maxLength: 50   
        IsAdultSignature  :
          type: boolean
          description: Denotes the signature is received from an adult.    
            The possible values are “Yes/No” where “Yes” signifies that the signature was received from an adult person and “No” signifies that it is not an adult signature  
        DeliveryCODRequired :
          type: boolean
          description: 'To determine if DeliveryCOD is necessary or not. The options are <yes/no>.   
            Example: When "Yes" is selected, Delivery COD is mandatory, while "No" indicates it is not required.'   
        SuppressUserNotification :
          type: boolean
          description: This allows to prevent or disable notifications intended for a user.   
            The potential values are "Yes/No," where "Yes" signifies that the notifications should not be sent, and "No" signifies that notification has to be sent.
        PurchaseOrderNumber :
          type: string
          description: PurchaseOrderNumber serves as a unique identifier to track the purchase order.
          minLength: 0
          maxLength: 50
        ReferenceNumber :
          type: string
          description: ReferenceNumber serves as a unique identifier to track the purchase order. 
          minLength: 0
          maxLength: 50  
        ShortCodeOptIn :
          type: boolean
          description: It signifies whether a shortcodeoptin is required or not.  
            The potential values are "Yes/No," where "Yes" signifies that the shortcodeoptin is required, and "No" signifies that it is not required. 
        CollectionLocation:
          $ref: '#/components/schemas/Collectionlocation'
        DeliveryLocation:
          $ref: '#/components/schemas/Deliverylocation'
      example:
        Refrigerated: false
        TrackingNumber: ''
        ShippingLabelSize: 4x8
        Format: pdf
        RequestedBy:
        Description: 'Fragile Handle with care: Glass material'
        Comments: Inflammable
        CollectionContactName:
        CollectionCODRequired: false
        CODAmount: 20
        CollectionSignatureRequired: false
        Weight: 200
        Quantity: 1
        PriceSet: b6ec8de4-852a-445f-8f3e-c56b8b396111
        DeclaredValue: 129
        DeliverySignatureRequired: true
        SignatureType: direct
        IsAdultSignature: true
        DeliveryCODRequired: false
        SuppressUserNotification: false
        PurchaseOrderNumber: '55555'
        ReferenceNumber:
        ShortCodeOptIn: false
        CollectionLocation:
          ContactName: Johnsons-6
          CompanyName: Johnsons-6
          AddressLine1: 2334 Cedar Crest Blvd
          AddressLine2: ''
          City: Dallas
          State: TX
          PostalCode: '75203'
          Country: United States
          Comments:
          Email: pharma@yopmail.com
          Phone: '3333344445'
          LatitudeLongitude:
        DeliveryLocation:
          ContactName: Tom Holland-525
          CompanyName: Medicare-525
          AddressLine1: 10311 Joaquin Dr
          AddressLine2: ''
          City: Dallas
          State: TX
          PostalCode: '75229'
          Country: United States
          Comments:
          Email: uzumaki@yopmail.com
          Phone: "+914444444446"
          LatitudeLongitude:
      xml:
        name: CreateOrderInDto   
    CreateOrderOutDto:
      type: object
      properties:
        UID:
          type: string
          description: The ID generated by the STAT system acts as a unique identifier for an order
          minLength: 0
          maxLength: 50
        TrackingNumber :
          type: string
          description: The tracking number acts as a unique identifier to track the package in real-time during the shipment.
          minLength: 0
          maxLength: 50
        CollectionLocation:
          $ref: '#/components/schemas/CollectionLocation'
        DeliveryLocation:
          $ref: '#/components/schemas/DeliveryLocation'
        Refrigerated :
          type: boolean
          description: This indicates whether the product is refrigerated prior to or during shipment.  
            The potential values are "Yes/No," where "Yes" signifies that the product is refrigerated, and "No" signifies that it is not refrigerated.  
        Description :
          type: string
          description: This is a free text field where the special instructions about the product, shipment are added 
          minLength: 0
          maxLength: 2000  
        Comments :
          type: string
          description: This is a free text field where the special instructions about the product, shipment are added
          minLength: 0
          maxLength: 2000    
        CollectionSignatureRequired :
          type: boolean
          description: This indicates whether obtaining a signature from the recipient is necessary after package collection.  
            The potential values are "Yes/No," where "Yes" signifies that the signature is required, and "No" signifies that it is not required.  
        DeliverySignatureRequired :
          type: boolean
          description: Indicates whether a signature is necessary from the recipient upon package delivery.  
            The potential values are "Yes/No," where "Yes" signifies that the signature is required, and "No" signifies that it is not required.  
        SuppressUserNotification :
          type: boolean
          description: This allows to prevent or disable notifications intended for a user.  
            The potential values are "Yes/No," where "Yes" signifies that the notifications should not be sent, and "No" signifies that notification has to be sent.    
      example:
        UID: 7e30f2b8-b356-4a02-948c-4b7ebb166785
        TrackingNumber: ''
        collectionLocation:
          ContactName: Johnsons-6
          CompanyName: Johnsons-6
          AddressLine1: 2334 Cedar Crest Blvd
          AddressLine2: ''
          City: Dallas
          State: TX
          PostalCode: '75203'
          Country: United States
          Comments:
          Email: pharma@yopmail.com
          Phone: '3333344445'
        deliveryLocation:
          ContactName: Tom Holland-525
          CompanyName: Medicare-525
          AddressLine1: 10311 Joaquin Dr
          AddressLine2: ''
          City: Dallas
          State: TX
          PostalCode: '75229'
          Country: United States
          Comments:
          Email: uzumaki@yopmail.com
          Phone: "+914444444446"
        Refrigerated: false
        Description: 'Fragile Handle with care: Glass material'
        Comments: Inflammable
        CollectionSignatureRequired: false
        DeliverySignatureRequired: true
        SuppressUserNotification: false
      xml:
        name: CreateOrderOutDto  
